version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - ./requirements/nginx/log:/var/log/nginx/
      - wp-volume:/var/www/
    restart: always
    networks:
      - inception

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    networks:
      - inception
  
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    environment:
      -  DB_NAME=${DB_NAME}
      -  DB_USER=${DB_USER}
      -  DB_PASS=${DB_PASS}
      -  WP_ADMIN=${WP_ADMIN}
      -  WP_PASS=${WP_PASS}
      -  WP_USER_PASS=${WP_USER_PASS}
      -  WP_USERNAME=${WP_USERNAME}
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/
    restart: always
    networks:
      - inception

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:  
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
      driver: bridge

